services:
  web:
    build:
      context: .
      dockerfile: php/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comp_sec_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
